version: '3'

services:
  db:
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: webmonitoring
      POSTGRES_USER: webmonitoring
      POSTGRES_PASSWORD: webmonitoring
      POSTGRES_NAME: webmonitoring
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
