# Generated by Django 3.2.7 on 2022-07-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='site',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
