# Generated by Django 3.2.7 on 2022-07-25 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20220724_0936'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='site',
            unique_together={('url', 'user_id')},
        ),
    ]
