# Generated by Django 3.2.7 on 2022-07-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitehistory',
            name='status_code',
            field=models.IntegerField(null=True),
        ),
    ]
